# Generated by Django 6.0.1 on 2026-01-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('types', models.JSONField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('image_url', models.URLField()),
                ('name_reversed', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
